version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./var/data/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    php:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ${APPLICATIONS}:/var/www/applications
            - ./var/logs/applications:/var/www/logs
        environment:
            - XDEBUG_REMOTE_HOST=${HOST_IP}
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx
    memcached:
        build: ./memcached
        volumes:
            - ./var/data/memcached:/var/lib/memcached
        ports:
            - "11211"
        depends_on:
            - php
